:bug: resolve githook related config and formatted code

diff --git a/scripts/pre-commit/pre-commit b/scripts/pre-commit/pre-commit
--- a/scripts/pre-commit/pre-commit
+++ b/scripts/pre-commit/pre-commit
@@ -1,32 +1,31 @@
 #!/usr/bin/env bash
-echo "Running auto formatter"
-./gradlew detekt --auto-correct
+echo "
+===============
+|  Running detekt...
+===============
+"
 
-echo "Running detekt check..."
-LOG="/tmp/detekt-$(date +%s)"
-./gradlew detekt > $LOG
+./gradlew --no-daemon --stacktrace -PdisablePreDex detekt
 
-EXIT_CODE=$?
-if [ $EXIT_CODE -ne 0 ]; then
-  cat $LOG
-  rm $LOG
-  echo "***********************************************"
-  echo "                 Detekt failed                 "
-  echo " Please fix the above issues before committing "
-  echo "***********************************************"
-  exit $EXIT_CODE
-fi
-rm $LOG
+detektStatus=$?
 
-echo "Running ktlint check..."
+# return 1 exit code if running checks fails
+[ $detektStatus -ne 0 ] && exit 1
 
-./gradlew ktlintFormat
+#echo "Running ktlintFormat..."
+#
+#./gradlew ktlintFormat
 
-STATUS=$?
-if [ $STATUS -ne 0 ]; then
-  echo "***********************************************"
-  echo "                 ktlint failed                 "
-  echo " Please fix the above issues before committing "
-  echo "***********************************************"
-  exit $STATUS
-fi
+echo "
+===================
+|  Running ktlintCheck...
+===================
+"
+
+./gradlew --no-daemon --stacktrace -PdisablePreDex ktlintCheck
+
+checkStyleStatus=$?
+
+# return 1 exit code if running checks fails
+[ $checkStyleStatus -ne 0 ] && exit 1
+exit 0
